import { StyleSheet } from 'react-native';

export const palette = {
  bg: '#07111f',
  panel: '#0f1b2d',
  panel2: '#13243b',
  text: '#eef4ff',
  muted: '#a9b7cf',
  accent: '#87d7ff',
  accentSoft: 'rgba(135,215,255,0.14)',
  accent2: '#ffd66b',
  good: '#8df0c8',
  border: 'rgba(255,255,255,0.10)',
  danger: '#ff9fa7',
};

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: palette.bg },
  container: { padding: 20, paddingBottom: 48, gap: 16 },
  card: {
    backgroundColor: palette.panel,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: palette.border,
    padding: 18,
    gap: 12,
  },
  kicker: { color: palette.accent, fontSize: 12, fontWeight: '700', letterSpacing: 1.1 },
  heroTitle: { color: palette.text, fontSize: 30, fontWeight: '800', lineHeight: 34 },
  sectionTitle: { color: palette.text, fontSize: 22, fontWeight: '800' },
  flowTitle: { color: palette.text, fontSize: 16, fontWeight: '700' },
  body: { color: palette.muted, fontSize: 15, lineHeight: 22 },
  muted: { color: palette.muted, fontSize: 14 },
  microMeta: { color: palette.muted, fontSize: 12, lineHeight: 18 },
  flowItem: { borderRadius: 16, backgroundColor: palette.panel2, padding: 14, gap: 6 },
  listItem: { borderRadius: 16, backgroundColor: palette.panel2, padding: 14, gap: 6 },
  selectorCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.panel2,
    padding: 14,
    gap: 4,
  },
  selectorCardActive: { borderColor: palette.accent, backgroundColor: palette.accentSoft },
  badgeRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  badge: {
    color: palette.accent,
    backgroundColor: palette.accentSoft,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    overflow: 'hidden',
    fontSize: 12,
    fontWeight: '600',
  },
  fieldWrap: { gap: 8 },
  label: { color: palette.muted, fontSize: 13, fontWeight: '600' },
  input: {
    backgroundColor: palette.bg,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: palette.border,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: palette.text,
    fontSize: 15,
  },
  textarea: { minHeight: 92 },
  rowBetween: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 12 },
  entryCard: { backgroundColor: palette.panel2, borderRadius: 16, padding: 14, gap: 10, marginTop: 12 },
  secondaryButton: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: palette.border,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  secondaryButtonText: { color: palette.text, fontWeight: '700' },
  primaryButton: {
    marginTop: 18,
    backgroundColor: palette.accent,
    paddingVertical: 14,
    borderRadius: 999,
    alignItems: 'center',
  },
  primaryButtonDisabled: { opacity: 0.5 },
  primaryButtonText: { color: '#00111f', fontWeight: '800', fontSize: 15 },
  removeText: { color: palette.danger, fontWeight: '700' },
  statusWrap: {
    marginTop: 10,
    gap: 8,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: 'rgba(7,17,31,0.55)',
    padding: 14,
  },
  statusText: { fontWeight: '600' },
  good: { color: palette.good },
  warn: { color: palette.accent2 },
  successText: { marginTop: 12, color: palette.good, fontWeight: '700', lineHeight: 20 },
  noteBox: { marginTop: 8, borderRadius: 16, padding: 14, backgroundColor: palette.accentSoft, gap: 6 },
  noteTitle: { color: palette.text, fontWeight: '800', fontSize: 15 },
  navButton: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.panel2,
    padding: 18,
    gap: 8,
  },
  navButtonTitle: { color: palette.text, fontWeight: '800', fontSize: 18 },
});
