prompt Creating Music Auditions Platform schema

create table map_organizations (
  organization_id        varchar2(100) primary key,
  name                   varchar2(200) not null,
  location               varchar2(200),
  organization_type      varchar2(120),
  summary                clob,
  contact_email          varchar2(320),
  website_url            varchar2(500),
  created_at             timestamp default current_timestamp not null
);

create table map_audition_events (
  audition_event_id      varchar2(100) primary key,
  organization_id        varchar2(100) not null references map_organizations(organization_id),
  title                  varchar2(200) not null,
  location               varchar2(200),
  deadline_date          date,
  genre                  varchar2(120),
  audition_count_min     number(3) not null,
  audition_count_max     number(3) not null,
  description            clob,
  created_at             timestamp default current_timestamp not null,
  constraint map_audition_event_ck check (audition_count_min <= audition_count_max)
);

create table map_audition_requirements (
  requirement_id         number generated by default as identity primary key,
  audition_event_id      varchar2(100) not null references map_audition_events(audition_event_id) on delete cascade,
  requirement_text       varchar2(4000) not null,
  display_order          number default 1 not null
);

create table map_audition_focuses (
  focus_id               number generated by default as identity primary key,
  audition_event_id      varchar2(100) not null references map_audition_events(audition_event_id) on delete cascade,
  focus_name             varchar2(200) not null,
  display_order          number default 1 not null
);

create table map_musicians (
  musician_id            varchar2(100) primary key,
  email                  varchar2(320) not null unique,
  password_hint          varchar2(200),
  stage_label            varchar2(200),
  full_name              varchar2(200) not null,
  primary_instrument     varchar2(200),
  city                   varchar2(200),
  bio                    clob,
  created_at             timestamp default current_timestamp not null
);

create table map_registrations (
  registration_id        number generated by default as identity primary key,
  musician_id            varchar2(100) not null references map_musicians(musician_id) on delete cascade,
  audition_event_id      varchar2(100) not null references map_audition_events(audition_event_id) on delete cascade,
  registered_at          date not null,
  registration_status    varchar2(30) not null,
  created_at             timestamp default current_timestamp not null,
  constraint map_registration_uq unique (musician_id, audition_event_id),
  constraint map_registration_status_ck check (registration_status in ('registered','uploading','ready'))
);

create table map_tapes (
  tape_id                varchar2(100) primary key,
  registration_id        number not null references map_registrations(registration_id) on delete cascade,
  piece_title            varchar2(300),
  composer               varchar2(300),
  duration_text          varchar2(50),
  media_link             varchar2(1000),
  notes                  clob,
  created_at             timestamp default current_timestamp not null
);

create index map_audition_events_org_ix on map_audition_events (organization_id);
create index map_registrations_musician_ix on map_registrations (musician_id);
create index map_registrations_event_ix on map_registrations (audition_event_id);
create index map_tapes_registration_ix on map_tapes (registration_id);
